# Regenerated by scripts/update-homebrew-formula.sh after each release tag.
# Edit that script, not this file, when the formula's structure needs to change.

class OxideCode < Formula
  desc "Terminal-based AI coding assistant written in Rust"
  homepage "https://github.com/hakula139/oxide-code"
  version "0.1.0-alpha.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hakula139/oxide-code/releases/download/v0.1.0-alpha.1/oxide-code-aarch64-apple-darwin.tar.gz"
      sha256 "adb399884afee3539103f7a5a2c8d5f78f1951f6c3762b7b79d92a519d891919"
    end
    on_intel do
      url "https://github.com/hakula139/oxide-code/releases/download/v0.1.0-alpha.1/oxide-code-x86_64-apple-darwin.tar.gz"
      sha256 "f0762669729fec25b7d3f2f1911f250befd56a06d577f11b0367c4d16bdfabfb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hakula139/oxide-code/releases/download/v0.1.0-alpha.1/oxide-code-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "063598d0f801d4d53628cda63e573e6af57288c116af35d04d81c3f959ad6e9b"
    end
  end

  def install
    bin.install "ox"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ox --version")
  end
end
