#!/usr/bin/env bash
# Regenerate Formula/oxide-code.rb from a release tag's published artifacts.
#
# Run after a release tag's `upload-assets` job has finished, since the script
# fetches each `.sha256` sidecar from the GitHub Release. Manual flow:
#
#   ./scripts/update-homebrew-formula.sh vX.Y.Z
#   git commit -am "chore(release): refresh Homebrew formula for vX.Y.Z"
#   git push

set -euo pipefail

if [[ "$#" -ne 1 ]]; then
  echo "usage: $0 <vX.Y.Z>" >&2
  exit 2
fi

tag="$1"
if [[ "$tag" != v* ]]; then
  echo "Error: tag must start with 'v' (got: $tag)" >&2
  exit 1
fi

version="${tag#v}"
formula="Formula/oxide-code.rb"
base="https://github.com/hakula139/oxide-code/releases/download/${tag}"

# Fetch the `.sha256` sidecar published alongside each archive and trim to the
# digest column (the file is `<digest>  <filename>`). The sidecar is named
# `<bin>-<target>.sha256`, with no archive extension.
fetch_sha() {
  curl -fsSL "${base}/$1.sha256" | awk '{print $1}'
}

mac_arm_sha=$(fetch_sha "oxide-code-aarch64-apple-darwin")
mac_x86_sha=$(fetch_sha "oxide-code-x86_64-apple-darwin")
linux_x86_sha=$(fetch_sha "oxide-code-x86_64-unknown-linux-gnu")

cat >"${formula}" <<EOF
# Regenerated by scripts/update-homebrew-formula.sh after each release tag.
# Edit that script, not this file, when the formula's structure needs to change.

class OxideCode < Formula
  desc "Terminal-based AI coding assistant written in Rust"
  homepage "https://github.com/hakula139/oxide-code"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/oxide-code-aarch64-apple-darwin.tar.gz"
      sha256 "${mac_arm_sha}"
    end
    on_intel do
      url "${base}/oxide-code-x86_64-apple-darwin.tar.gz"
      sha256 "${mac_x86_sha}"
    end
  end

  on_linux do
    on_intel do
      url "${base}/oxide-code-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_x86_sha}"
    end
  end

  def install
    bin.install "ox"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ox --version")
  end
end
EOF

printf 'Updated %s to %s\n' "${formula}" "${tag}"
